-- English product descriptions, shown when the site is in English.
-- Runs after data.sql (see spring.sql.init.data-locations).
UPDATE product SET description_en = 'A multifunctional tool made of black stainless steel. It includes pliers, a knife, scissors, screwdrivers, an opener and other handy tools. Folded length is 11 cm.' WHERE name = 'Multifunctional Multitool';
UPDATE product SET description_en = 'A car detailing kit with microfibre cloths, brushes and sponges. Everything is packed in a compact black bag for easy storage and transport.' WHERE name = 'Car cleaning set';
UPDATE product SET description_en = 'A 20,000 mAh power bank in a black case. It has USB and USB-C ports and supports fast charging for phones, headphones and other USB devices.' WHERE name = 'Power Bank 20.000 mAh';
UPDATE product SET description_en = 'An LED flashlight with a black metal body and a USB charging port. It has five lighting modes and a waterproof body, so it works in all kinds of conditions.' WHERE name = 'Rechargeable LED Flashlight';
UPDATE product SET description_en = 'A beard care set with a brush, a comb, scissors and beard oil. Everything comes in a compact, practical black decorative box.' WHERE name = 'Beard Grooming Set';
UPDATE product SET description_en = 'A cordless electric trimmer with a black and silver body and several attachments for different trimming lengths. It charges over USB and comes with a cleaning brush.' WHERE name = 'Electrical beard trimmer';
UPDATE product SET description_en = 'A classic, compact wallet made of genuine leather, in brown with a perfect texture.' WHERE name = 'Classic leather wallet';
UPDATE product SET description_en = 'A magnetic phone holder with a black aluminium body and a strong magnet. It clips onto the air vent in the car and holds the phone firmly in place.' WHERE name = 'Magnetic phone holder';
UPDATE product SET description_en = 'A Bluetooth tracker in a compact black case, 36 mm across. It connects to your phone and helps you find the things it is attached to through a mobile app.' WHERE name = 'Bluetooth Key Finder';
UPDATE product SET description_en = 'A set of three stainless steel barbecue tools with black handles: tongs, a spatula and a fork. It comes in a black storage bag.' WHERE name = 'BBQ Grill Tool Set';
UPDATE product SET description_en = 'A 500 ml thermos bottle made of stainless steel with a matte black finish. The double insulated wall keeps drinks hot or cold, and the cap seals tight so nothing leaks.' WHERE name = 'Stainless steel bottle';
UPDATE product SET description_en = 'A gift set with two whiskey glasses and four chilling stones made of natural stone. It comes in an elegant black gift box.' WHERE name = 'Whiskey Glass Set';
UPDATE product SET description_en = 'A detailed 1:24 scale metal model of a sports car, with a metal body, rubber tyres, a detailed interior and doors that open.' WHERE name = 'Miniature car model';
UPDATE product SET description_en = 'A folding knife made of premium Damascus steel with a distinctive patterned finish, 20 cm long in total (9 cm blade). It comes with a leather belt sheath and a small sharpener with a decorated metal handle.' WHERE name = 'Pocket knife';
UPDATE product SET description_en = 'A fitness set with black lifting straps and hand grip trainers. The fabric straps have reinforced stitching, and the grip trainers are made of sturdy plastic with rubber handles.' WHERE name = 'Gym straps';
UPDATE product SET description_en = 'A fishing kit packed in a compact plastic box with compartments. It contains lures, hooks, swivels and other fishing basics.' WHERE name = 'Fishing Tackle Set';
UPDATE product SET description_en = 'A survival kit with the basic tools for outdoor activities, packed in a black waterproof pouch. It includes a multitool, a compass, a whistle and a fire starter.' WHERE name = 'Outdoor Survival Kit';
UPDATE product SET description_en = 'A precision screwdriver set with a metal handle and 24 different bits. Everything is organised in a compact black box with a magnetic bit holder.' WHERE name = 'Screwdriver Set';
UPDATE product SET description_en = 'An elegant mechanical watch with a classic retro design and a 38 mm stainless steel case. It has a silver dial with gold hands and a brown leather strap with hand-stitched details.' WHERE name = 'Mechanical wristwatch';
UPDATE product SET description_en = 'A walnut cigar humidor with a glass lid and a built-in digital hygrometer for precise humidity control. The set includes a humidifier, a cigar cutter, a metal key, an elegant leather case and a lighter.' WHERE name = 'Cigar set';
